### ISSUE TITLE
why is pids argument pids= error... 

### ISSUE THREAD

**Issue by simhigo** [SkyLined/CrashInfo#1]
* Terminating any running instances of Microsoft Edge...
* Activating Microsoft Edge and opening http://www.naver.com...
+ MicrosoftEdge.exe process id = 6096
+ MicrosoftEdgeCP.exe process id = 4540
+ RuntimeBroker.exe process id = 4424
+ browser_broker.exe process id = 5892
* Starting C:\Python27\python.exe C:\CrashInfo\ci.py --pids=4424,58926096,4540,
['4424', '58926096', '4540', '']

**Comment by SkyLined** [comment]
Hi Simhigo, thank you for using CrashInfo at this early stage and reporting bugs! CrashInfo is currently very much in alpha testing and this does mean it will have some bugs. I believe the issue you are seeing has already been addressed. Can you download the latest and let me know if it resolves the issue for you?

**Comment by simhigo** [comment]
Edgedbg & crash info last version.

Edgedbg Bug.

Edgedbg.cpp 

Line 176, 177 Line

before
```cpp
std::basic_string<TCHAR> sAllProcessIds = sRuntimeBrokerProcessId + _T(",") + sBrowserBrokerProcessId + sMicrosoftEdgeProcessId + _T(",") + sMicrosoftEdgeCPProcessId + _T(",");
```

after
```cpp
std::basic_string<TCHAR> sAllProcessIds = sMicrosoftEdgeProcessId + _T(",") + sBrowserBrokerProcessId + _T(",") +sRuntimeBrokerProcessId + _T(",") + sMicrosoftEdgeCPProcessId;
```

fix it!

**Comment by SkyLined** [comment]
If I understand correctly, you are reporting a bug in EdgeDbg, not CrashInfo. Also, that particular issue is already fixed, see:
https://github.com/SkyLined/EdgeDbg/blob/master/EdgeDbg.cpp#L178

      std::basic_string<TCHAR> sAllProcessIds = sRuntimeBrokerProcessId + _T(",") + sBrowserBrokerProcessId +  _T(",") +
                                                sMicrosoftEdgeProcessId + _T(",") + sMicrosoftEdgeCPProcessId;

**Comment by SkyLined** [comment]
I only just noticed issues were accidentally turned off in EdgeDbg, thanks for helping me fix that!
